version: 0.2
env:
  parameter-store:
    S3_BUCKET: "S3_BUCKET"

phases:
  pre_build:
    commands:
      - echo 'Pre Build Phase ...'
      - curl -sL https://rpm.nodesource.com/setup_17.x | bash -
      - yum -y install nodejs npm --skip-broken
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date` and started Apache server
      - rm -R node_modules
      - echo ${BUCKET_NAME}
      - aws s3 cp --recursive --acl public-read-write build s3://${S3_BUCKET}/ 
      - rm -R build
      
artifacts:
  # type: zip
  # paths:
  #   - '*'
  files:
    - "**/*"
  name: $(AWS_REGION)-$(date +%Y-%m-%d) 

  # discard-paths: no