version: 0.2
run-as: root

env:
  parameter-store:
    BUCKET: "S3_BUCKET"
    BUCKET_NAME: "BUCKET_NAME"

phases:
  install:
      runtime-versions:
          docker: 18
  pre_build:
    commands:
      - echo 'Pre Build Phase ...'
      - echo my s3 bucket name "$BUCKET" 
      - curl -sL https://rpm.nodesource.com/setup_17.x | bash -
      - yum -y install nodejs npm --skip-broken
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date` and started Apache server
      - rm -R node_modules
      - echo "${BUCKET_NAME}"
      - aws s3 cp build s3://${BUCKET} --recursive

eb_codebuild_settings:
  CodeBuildServiceRole: AdministratorAccess-AWSElasticBeanstalk
  ComputeType: 
  Image: 354220933236.dkr.ecr.us-east-1.amazonaws.com/movie-app:latest


artifacts:
  type: zip
  # paths:
  #   - '*'
  files: 
    # - imagedefinitions.json
    - "**/*"
  name: $(AWS_REGION)-$(date +%Y-%m-%d)
  # discard-paths: no