# FROM node:alpine
# WORKDIR /public
# COPY package.json ./
# COPY package-lock.json ./
# COPY ./ ./
# RUN npm i

FROM node:latest

WORKDIR /movie-app

COPY ["package.json", "package-lock.json", "./"]
RUN ls
RUN npm install --
COPY . .

EXPOSE 3000

CMD ["npm", "run", "start"]
