apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: react-app
  name: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: react-app
    spec:
      containers:
      - image: 032840272187.dkr.ecr.us-east-2.amazonaws.com/frontend/react-node:v1
        name: app
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 3000
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: react-webapp
  labels:
    run: react-webapp
spec:
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: react-webapp
  type: NodePort